### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mishoboss** [functionpointer/mqtt-chromium-control#1]
I'm interested in using your work the same way you do - Home Assistant and Linux kiosks. I will be very appreciated if you can do a bit of documentation. :) 

Also, I see there is hardcoded stuff here and there, would be awesome if this is made as generic as possible.

**Comment by functionpointer** [comment]
Thanks for your interest, I didn't think anyone would use this.

The program itself should be pretty generic, only the service file has hard-coded stuff.

I have added a small README. I hope it answers your questions. If not, feel free to ask.
